name: Duumori CI

on:
  push:
    branches:
      - test-automation
  pull_request:
    branches:
      - test-automation

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-firefox:latest
        options: --privileged
        ports:
          - "4444:4444"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          cd weather-app/frontend
          npm install
          cd ../backend
          npm install
          cd ../test
          npm install
          cd ../
      
      - name: Load environment variables
        run: |
          cd weather-app/backend
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" > .env
          echo "CORS_ALLOW=http://localhost:8080" >> .env
          echo "PORT=3000" >> .env
          cd ../frontend
          echo "VITE_API=http://localhost:3000" > .env
          cd ../test
          echo "IS_CI=true" > .env
          echo "FRONTEND=frontend:8080" >> .env
          cd ../

      - name: Clean up stray docker containers
        run: |
          docker ps -a -q | xargs docker rm -f

      - name: Run docker
        run: |
          cd weather-app
          docker compose up -d
      
      - name: Check active ports
        run: |
          echo "Port 4444 (Selenium):"
          sudo lsof -i :4444
          echo "Port 8080 (Vite):"
          sudo lsof -i :8080
          echo "Port 3000 (Express):"
          sudo lsof -i :3000

      - name: Wait for services to be ready
        run: |
          echo "Waiting for Selenium to be ready..."
          until curl --silent --fail http://localhost:4444/wd/hub/status; do
            echo "Waiting for Selenium WebDriver to be ready..."
            sleep 5
          done
          echo "Selenium ready"

      - name: Run selenium tests
        run: |
          cd weather-app/test
          node index.js

      - name: Shut down Docker containers
        run: |
          cd weather-app
          docker compose down
