name: Duumori CI

on:
  push:
    branches:
      - test-automation
  pull_request:
    branches:
      - test-automation

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-firefox:latest
        options: --privileged
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          cd weather-app/frontend
          npm install
          cd ../backend
          npm install
          cd ../test
          npm install
          cd ../
      
      - name: Load environment variables
        run: |
          cd backend
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" > .env
          echo "CORS_ALLOW=http://localhost:8080" > .env
          echo "PORT=3000" > .env
          cd ../frontend
          echo "VITE_API=http://localhost:3000" > .env
          cd ../

      - name: Run docker
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          sleep 30

      - name: Run selenium tests
        run: |
          cd test
          node index.js

      - name: Shut down Docker containers
        run: |
          docker-compose down
